{literal}
  <script id="budget-row-template" type="text/x-handlebars-template">
    <tr>
      <td></td>
      <td>
          <input 
            type="text" 
            placeholder="Расходы"
            class="form-text" 
            value=""
            name="costs_name__{{dt}}[]"
          >
        </td>
      <td>&nbsp;&nbsp;-&nbsp;&nbsp;</td>
      <td>
        <input 
          type="text" 
          placeholder="Сумма"
          value="" 
          class="form-text" 
          name="costs_amount__{{dt}}[]"
        >
      </td>
      <td></td>
    </tr>
  </script>
{/literal}